# Generated by Django 6.0.1 on 2026-01-22 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('mechanics', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTripInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated inspection ID in format INSP-XXXX', max_length=20, unique=True)),
                ('inspection_date', models.DateField(help_text='Date of the inspection')),
                ('route', models.CharField(help_text='Route for the trip (e.g., Lusaka - Ndola)', max_length=200)),
                ('approved_driving_hours', models.CharField(help_text='Approved driving hours (e.g., 6 hrs 50 mins)', max_length=20)),
                ('approved_rest_stops', models.IntegerField(default=0, help_text='Number of approved rest stops')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current status of the inspection', max_length=20)),
                ('approval_status_updated_at', models.DateTimeField(blank=True, help_text='Timestamp when approval status was last updated', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Fleet Manager who approved/rejected this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspections', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(help_text='Driver assigned to this inspection', on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='drivers.driver')),
                ('mechanic', models.ForeignKey(blank=True, help_text='Mechanic assigned to this inspection (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='mechanics.mechanic')),
                ('supervisor', models.ForeignKey(help_text='Transport Supervisor who created this inspection', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_inspections', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle being inspected', on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Pre-Trip Inspection',
                'verbose_name_plural': 'Pre-Trip Inspections',
                'ordering': ['-inspection_date', '-created_at'],
                'indexes': [models.Index(fields=['inspection_id'], name='inspections_inspect_7858fb_idx'), models.Index(fields=['status'], name='inspections_status_30a247_idx'), models.Index(fields=['inspection_date'], name='inspections_inspect_1e22b8_idx')],
            },
        ),
    ]
