# Generated by Django 6.0.1 on 2026-01-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFitnessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_test_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Result of alcohol test', max_length=10)),
                ('alcohol_test_remarks', models.TextField(blank=True, help_text='Remarks for alcohol test')),
                ('temperature_check_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Result of temperature check', max_length=10)),
                ('temperature_value', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature value in Celsius (e.g., 36.7)', max_digits=4, null=True)),
                ('fit_for_duty', models.BooleanField(default=True, help_text='Whether driver is fit for duty')),
                ('medication_status', models.BooleanField(default=False, help_text='Whether driver is on medication')),
                ('medication_remarks', models.CharField(blank=True, help_text='Details about medication if applicable', max_length=200)),
                ('no_health_impairment', models.BooleanField(default=True, help_text='Driver has no health impairments')),
                ('fatigue_checklist_completed', models.BooleanField(default=False, help_text='Whether fatigue checklist was completed')),
                ('fatigue_remarks', models.CharField(blank=True, help_text='Remarks about fatigue check', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='health_fitness', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Health & Fitness Check',
                'verbose_name_plural': 'Health & Fitness Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
