# Generated by Django 6.0.1 on 2026-01-22 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_healthfitnesscheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_fitness', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], help_text='Certificate of fitness status', max_length=10)),
                ('road_tax_valid', models.BooleanField(default=False, help_text='Road tax is valid')),
                ('insurance_valid', models.BooleanField(default=False, help_text='Insurance is valid')),
                ('trip_authorization_signed', models.BooleanField(default=False, help_text='Trip authorization has been signed')),
                ('logbook_present', models.BooleanField(default=False, help_text='Vehicle logbook is present')),
                ('driver_handbook_present', models.BooleanField(default=False, help_text='Driver handbook is present')),
                ('permits_valid', models.BooleanField(default=False, help_text='All permits are valid')),
                ('ppe_available', models.BooleanField(default=False, help_text='Personal protective equipment is available')),
                ('route_familiarity', models.BooleanField(default=False, help_text='Driver is familiar with the route')),
                ('emergency_procedures_known', models.BooleanField(default=False, help_text='Driver knows emergency procedures')),
                ('gps_activated', models.BooleanField(default=False, help_text='GPS tracking is activated')),
                ('safety_briefing_provided', models.BooleanField(default=False, help_text='Safety briefing has been provided')),
                ('rtsa_clearance', models.BooleanField(default=False, help_text='RTSA clearance obtained')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact information', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Documentation & Compliance Check',
                'verbose_name_plural': 'Documentation & Compliance Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineFluidCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Engine & Fluid Check',
                'verbose_name_plural': 'Engine & Fluid Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Functional Check',
                'verbose_name_plural': 'Functional Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteriorCabinCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Interior & Cabin Check',
                'verbose_name_plural': 'Interior & Cabin Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEquipmentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Safety Equipment Check',
                'verbose_name_plural': 'Safety Equipment Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExteriorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Vehicle Exterior Check',
                'verbose_name_plural': 'Vehicle Exterior Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
