# Generated by Django 6.0.1 on 2026-01-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_documentationcompliance_enginefluidcheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('safety_training', 'Safety Training'), ('performance_review', 'Performance Review'), ('probationary_period', 'Probationary Period'), ('policy_acknowledgment', 'Policy Acknowledgment')], help_text='Type of corrective measure', max_length=50)),
                ('required', models.BooleanField(default=True, help_text='Whether this measure is required')),
                ('due_date', models.DateField(blank=True, help_text='Due date for completion', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the measure has been completed')),
                ('completed_date', models.DateField(blank=True, help_text='Date when measure was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the measure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='corrective_measures', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Corrective Measure',
                'verbose_name_plural': 'Corrective Measures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrivingBehaviorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_item', models.CharField(choices=[('obeys_traffic_rules', 'Obeys Traffic Rules'), ('safe_speed_distance', 'Safe Speed & Distance'), ('avoids_harsh_maneuvers', 'Avoids Harsh Maneuvers'), ('no_phone_use', 'No Phone Use While Driving'), ('headlights_visibility', 'Headlights & Visibility'), ('load_security', 'Load Security'), ('abnormal_sounds_reporting', 'Reports Abnormal Sounds'), ('no_overloading', 'No Overloading'), ('breakdown_reporting', 'Reports Breakdowns'), ('emergency_procedures', 'Follows Emergency Procedures'), ('contact_control_center', 'Contacts Control Center')], help_text='Driving behavior being checked', max_length=100)),
                ('status', models.BooleanField(help_text='Whether the behavior is compliant (Yes/No)')),
                ('remarks', models.CharField(blank=True, help_text='Additional remarks', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='driving_behaviors', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Driving Behavior Check',
                'verbose_name_plural': 'Driving Behavior Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnforcementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('suspension', 'Suspension'), ('final_warning', 'Final Warning'), ('termination', 'Termination'), ('other', 'Other')], help_text='Type of enforcement action', max_length=50)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the action has been applied')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the action', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (for suspension)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='enforcement_actions', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Enforcement Action',
                'verbose_name_plural': 'Enforcement Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_fault_submitted', models.BooleanField(default=False, help_text='Vehicle fault report submitted')),
                ('fault_notes', models.TextField(blank=True, help_text='Details about vehicle faults')),
                ('final_inspection_signed', models.BooleanField(default=False, help_text='Final inspection signed off')),
                ('compliance_with_policy', models.BooleanField(default=True, help_text='Driver complied with company policy')),
                ('attitude_cooperation', models.BooleanField(default=True, help_text='Driver showed good attitude and cooperation')),
                ('incidents_recorded', models.BooleanField(default=False, help_text='Any incidents recorded during trip')),
                ('incident_notes', models.TextField(blank=True, help_text='Details about incidents')),
                ('total_trip_duration', models.CharField(blank=True, help_text='Total trip duration (e.g., 6 hrs 30 mins)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='post_trip', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Post-Trip Report',
                'verbose_name_plural': 'Post-Trip Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_this_trip', models.IntegerField(default=0, help_text='Total violation points for this trip')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Risk level for this trip', max_length=10)),
                ('total_points_30_days', models.IntegerField(default=0, help_text='Total violation points in last 30 days')),
                ('risk_level_30_days', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Risk level for last 30 days', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Risk Score Summary',
                'verbose_name_plural': 'Risk Score Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripBehaviorMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_item', models.CharField(choices=[('speed_school_zone', 'Speed in School Zone'), ('speed_market_area', 'Speed in Market Area'), ('max_speed_open_road', 'Max Speed on Open Road'), ('railway_crossing', 'Railway Crossing'), ('toll_gate', 'Toll Gate'), ('hazardous_zone_speed', 'Speed in Hazardous Zone'), ('excessive_driving', 'Excessive Driving'), ('traffic_infractions', 'Traffic Infractions'), ('incidents', 'Incidents'), ('scheduled_breaks', 'Scheduled Breaks'), ('fatigue_reporting', 'Fatigue Reporting'), ('rest_stops_usage', 'Rest Stops Usage')], help_text='Behavior item being monitored', max_length=100)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('violation', 'Violation'), ('none', 'None')], help_text='Compliance status', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the behavior')),
                ('violation_points', models.IntegerField(default=0, help_text='Violation points (auto-calculated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='trip_behaviors', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Trip Behavior Monitoring',
                'verbose_name_plural': 'Trip Behavior Monitoring',
                'ordering': ['-created_at'],
            },
        ),
    ]
