# Generated by Django 6.0.1 on 2026-01-23 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_correctivemeasure_drivingbehaviorcheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_trip_inspection_score', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Score for pre-trip inspection completion (1-5)')),
                ('driving_conduct_score', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Score for driving conduct (1-5)')),
                ('incident_management_score', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Score for incident management (1-5)')),
                ('post_trip_reporting_score', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Score for post-trip reporting (1-5)')),
                ('compliance_documentation_score', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Score for compliance and documentation (1-5)')),
                ('overall_performance', models.CharField(choices=[('excellent', 'Excellent'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('non_compliant', 'Non-Compliant')], help_text='Overall performance level (auto-calculated)', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Additional comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Evaluation Summary',
                'verbose_name_plural': 'Evaluation Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(help_text='Name of the supervisor providing remarks', max_length=100)),
                ('remarks', models.TextField(help_text="Supervisor's remarks about the inspection")),
                ('recommendation', models.TextField(blank=True, help_text="Supervisor's recommendations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_remarks', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Supervisor Remarks',
                'verbose_name_plural': 'Supervisor Remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('supervisor', 'Supervisor'), ('mechanic', 'Mechanic')], help_text='Role of the person signing off', max_length=20)),
                ('signer_name', models.CharField(help_text='Name of the person signing off', max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when signed')),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='sign_offs', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Inspection Sign-Off',
                'verbose_name_plural': 'Inspection Sign-Offs',
                'ordering': ['-signed_at'],
                'constraints': [models.UniqueConstraint(fields=('inspection', 'role'), name='unique_inspection_role_signoff')],
                'unique_together': {('inspection', 'role')},
            },
        ),
    ]
