# Generated by Django 6.0.1 on 2026-01-23 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inspections', '0005_evaluationsummary_supervisorremarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('view', 'View'), ('export', 'Export')], help_text='Type of action performed', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object affected')),
                ('changes', models.JSONField(blank=True, help_text='JSON representation of changes made', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('content_type', models.ForeignKey(help_text='Type of object affected', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='inspections_timesta_abbd93_idx'), models.Index(fields=['content_type', 'object_id'], name='inspections_content_b51728_idx'), models.Index(fields=['user', '-timestamp'], name='inspections_user_id_8d8fb7_idx'), models.Index(fields=['action', '-timestamp'], name='inspections_action_8e1cf2_idx')],
            },
        ),
    ]
