# Generated by Django 6.0.1 on 2026-01-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginefluidcheck',
            name='inspection',
            field=models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='engine_fluid_checks', to='inspections.pretripinspection'),
        ),
        migrations.AlterField(
            model_name='functionalcheck',
            name='inspection',
            field=models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='functional_checks', to='inspections.pretripinspection'),
        ),
        migrations.AlterField(
            model_name='interiorcabincheck',
            name='inspection',
            field=models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='interior_cabin_checks', to='inspections.pretripinspection'),
        ),
        migrations.AlterField(
            model_name='safetyequipmentcheck',
            name='inspection',
            field=models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='safety_equipment_checks', to='inspections.pretripinspection'),
        ),
        migrations.AlterField(
            model_name='vehicleexteriorcheck',
            name='inspection',
            field=models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='exterior_checks', to='inspections.pretripinspection'),
        ),
    ]
