# Generated by Django 6.0.1 on 2026-01-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_enginefluidcheck_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretripinspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('post_trip_in_progress', 'Post-Trip In Progress'), ('post_trip_completed', 'Post-Trip Completed')], db_index=True, default='draft', help_text='Current status of the inspection', max_length=25),
        ),
    ]
