# Generated by Django 6.0.1 on 2026-01-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_increase_status_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pretripinspection',
            new_name='inspections_inspection_id_idx',
            old_name='inspections_inspect_7858fb_idx',
        ),
        migrations.RenameIndex(
            model_name='pretripinspection',
            new_name='inspections_date_idx',
            old_name='inspections_inspect_1e22b8_idx',
        ),
        # Skip AlterUniqueTogether - unique_together doesn't exist (already using UniqueConstraint)
    ]
