# Generated by Django 6.0.1 on 2026-01-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_pretripscoresummary'),
    ]

    operations = [
        # Removed AlterUniqueTogether - constraint doesn't exist in database
        migrations.AddField(
            model_name='documentationcompliance',
            name='certificate_of_fitness_valid',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is Certificate of Fitness valid? (Yes or No)', max_length=10),
        ),
        migrations.AddField(
            model_name='documentationcompliance',
            name='emergency_contact_employer',
            field=models.CharField(blank=True, help_text='Emergency contact - Employer (name and phone number)', max_length=100),
        ),
        migrations.AddField(
            model_name='documentationcompliance',
            name='emergency_contact_government',
            field=models.CharField(blank=True, help_text='Emergency contact - Government (name and phone number)', max_length=100),
        ),
        migrations.AddField(
            model_name='documentationcompliance',
            name='time_briefing_conducted',
            field=models.TimeField(blank=True, help_text='Time when briefing was conducted', null=True),
        ),
        migrations.AddField(
            model_name='pretripinspection',
            name='driver_rest_approved',
            field=models.BooleanField(default=False, help_text='Whether driver rest is approved (Yes or No)'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='brakes_steering_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Brakes & Steering score', max_digits=10),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='brakes_steering_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Brakes & Steering section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='brakes_steering_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Brakes & Steering checks score', max_digits=10),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='documentation_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Documentation section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='engine_fluid_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Engine/Fluid section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='functional_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Functional section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='health_fitness_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Health & Fitness section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='interior_cabin_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Interior section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='risk_status',
            field=models.CharField(choices=[('low_risk', 'Low Risk'), ('moderate_risk', 'Moderate Risk'), ('high_risk', 'High Risk'), ('critical_risk', 'Critical Risk')], default='high_risk', help_text='Risk status based on overall score', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='safety_equipment_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Safety Equipment section'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total number of questions across all sections'),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='vehicle_exterior_questions',
            field=models.IntegerField(default=0, help_text='Number of questions in Exterior section'),
        ),
        migrations.AlterField(
            model_name='documentationcompliance',
            name='certificate_of_fitness',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], help_text='Certificate of fitness status (legacy)', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentationcompliance',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact information (legacy)', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentationcompliance',
            name='rtsa_clearance',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='RTSA Clearance obtained (If Applicable)? (Yes or No)', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentationcompliance',
            name='safety_briefing_provided',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Was safety briefing provided? (Yes or No)', max_length=10),
        ),
        migrations.AlterField(
            model_name='pretripinspection',
            name='approved_driving_hours',
            field=models.CharField(choices=[('1:00', '1 hour'), ('1:15', '1 hrs 15 mins'), ('1:30', '1 hrs 30 mins'), ('1:45', '1 hrs 45 mins'), ('2:00', '2 hours'), ('2:15', '2 hrs 15 mins'), ('2:30', '2 hrs 30 mins'), ('2:45', '2 hrs 45 mins'), ('3:00', '3 hours'), ('3:15', '3 hrs 15 mins'), ('3:30', '3 hrs 30 mins'), ('3:45', '3 hrs 45 mins'), ('4:00', '4 hours'), ('4:15', '4 hrs 15 mins'), ('4:30', '4 hrs 30 mins'), ('4:45', '4 hrs 45 mins'), ('5:00', '5 hours'), ('5:15', '5 hrs 15 mins'), ('5:30', '5 hrs 30 mins'), ('5:45', '5 hrs 45 mins'), ('6:00', '6 hours'), ('6:15', '6 hrs 15 mins'), ('6:30', '6 hrs 30 mins'), ('6:45', '6 hrs 45 mins'), ('7:00', '7 hours'), ('7:15', '7 hrs 15 mins'), ('7:30', '7 hrs 30 mins'), ('7:45', '7 hrs 45 mins'), ('8:00', '8 hours'), ('8:15', '8 hrs 15 mins'), ('8:30', '8 hrs 30 mins'), ('8:45', '8 hrs 45 mins'), ('9:00', '9 hours'), ('9:15', '9 hrs 15 mins'), ('9:30', '9 hrs 30 mins'), ('9:45', '9 hrs 45 mins'), ('10:00', '10 hours'), ('10:15', '10 hrs 15 mins'), ('10:30', '10 hrs 30 mins'), ('10:45', '10 hrs 45 mins'), ('11:00', '11 hours'), ('11:15', '11 hrs 15 mins'), ('11:30', '11 hrs 30 mins'), ('11:45', '11 hrs 45 mins'), ('12:00', '12 hours'), ('12:15', '12 hrs 15 mins'), ('12:30', '12 hrs 30 mins'), ('12:45', '12 hrs 45 mins'), ('13:00', '13 hours'), ('13:15', '13 hrs 15 mins'), ('13:30', '13 hrs 30 mins'), ('13:45', '13 hrs 45 mins'), ('14:00', '14 hours'), ('14:15', '14 hrs 15 mins'), ('14:30', '14 hrs 30 mins'), ('14:45', '14 hrs 45 mins'), ('15:00', '15 hours'), ('15:15', '15 hrs 15 mins'), ('15:30', '15 hrs 30 mins'), ('15:45', '15 hrs 45 mins'), ('16:00', '16 hours'), ('16:15', '16 hrs 15 mins'), ('16:30', '16 hrs 30 mins'), ('16:45', '16 hrs 45 mins'), ('17:00', '17 hours'), ('17:15', '17 hrs 15 mins'), ('17:30', '17 hrs 30 mins'), ('17:45', '17 hrs 45 mins'), ('18:00', '18 hours'), ('18:15', '18 hrs 15 mins'), ('18:30', '18 hrs 30 mins'), ('18:45', '18 hrs 45 mins'), ('19:00', '19 hours'), ('19:15', '19 hrs 15 mins'), ('19:30', '19 hrs 30 mins'), ('19:45', '19 hrs 45 mins'), ('20:00', '20 hours'), ('20:15', '20 hrs 15 mins'), ('20:30', '20 hrs 30 mins'), ('20:45', '20 hrs 45 mins'), ('21:00', '21 hours'), ('21:15', '21 hrs 15 mins'), ('21:30', '21 hrs 30 mins'), ('21:45', '21 hrs 45 mins'), ('22:00', '22 hours'), ('22:15', '22 hrs 15 mins'), ('22:30', '22 hrs 30 mins'), ('22:45', '22 hrs 45 mins'), ('23:00', '23 hours'), ('23:15', '23 hrs 15 mins'), ('23:30', '23 hrs 30 mins'), ('23:45', '23 hrs 45 mins'), ('24:00', '24 hours')], help_text='Approved driving hours (dropdown from 1hr to 24hrs in 15min intervals)', max_length=20),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='documentation_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Documentation score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='documentation_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Documentation section score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='engine_fluid_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Engine/Fluid score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='engine_fluid_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Engine & Fluid checks score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='functional_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Functional score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='functional_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Functional checks score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='health_fitness_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Health & Fitness score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='health_fitness_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Health & Fitness section score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='interior_cabin_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Interior score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='interior_cabin_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Interior & Cabin checks score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='max_possible_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum possible total score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='safety_equipment_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Safety score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='safety_equipment_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Safety Equipment checks score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pre-trip checklist score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='vehicle_exterior_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max possible Exterior score', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='vehicle_exterior_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vehicle Exterior checks score', max_digits=10),
        ),
        migrations.CreateModel(
            name='BrakesSteeringCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(help_text='Item being checked', max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Pass or fail status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(help_text='Associated pre-trip inspection', on_delete=django.db.models.deletion.CASCADE, related_name='brakes_steering_checks', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Brakes & Steering Check',
                'verbose_name_plural': 'Brakes & Steering Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
