# Generated by Django 6.0.1 on 2026-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_alter_inspectionsignoff_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inspectionsignoff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='brakes_steering_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Brakes & Steering percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='brakes_steering_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Brakes & Steering section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='documentation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Documentation percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='documentation_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Documentation section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='engine_fluid_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Engine & Fluid percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='engine_fluid_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Engine & Fluid section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='functional_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Functional percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='functional_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Functional section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='health_fitness_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Health & Fitness percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='health_fitness_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Health & Fitness section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='interior_cabin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Interior & Cabin percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='interior_cabin_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Interior & Cabin section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='safety_equipment_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Safety Equipment percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='safety_equipment_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Safety Equipment section', max_length=20),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='vehicle_exterior_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vehicle Exterior percentage of total (out of 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pretripscoresummary',
            name='vehicle_exterior_risk',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk level for Vehicle Exterior section', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthfitnesscheck',
            name='max_possible_score',
            field=models.IntegerField(default=7, help_text='Maximum possible score for this section'),
        ),
        migrations.AlterField(
            model_name='healthfitnesscheck',
            name='section_score',
            field=models.IntegerField(default=0, help_text='Calculated score for this section (points earned)'),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='health_fitness_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Health & Fitness section score (points earned)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pretripscoresummary',
            name='risk_status',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Risk status based on overall score', max_length=20),
        ),
    ]
