# Generated by Django 6.0.1 on 2026-02-06 08:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_add_section_percentages_and_risk_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_checklist_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pre-checklist total score', max_digits=5)),
                ('pre_checklist_max', models.DecimalField(decimal_places=2, default=Decimal('64'), help_text='Pre-checklist max score', max_digits=5)),
                ('pre_checklist_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pre-checklist percentage (0-100)', max_digits=5)),
                ('pre_checklist_weighted', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pre-checklist weighted contribution (out of 50)', max_digits=5)),
                ('post_checklist_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Post-checklist total score', max_digits=5)),
                ('post_checklist_max', models.DecimalField(decimal_places=2, default=Decimal('28'), help_text='Post-checklist max score', max_digits=5)),
                ('post_checklist_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Post-checklist percentage (0-100)', max_digits=5)),
                ('post_checklist_weighted', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Post-checklist weighted contribution (out of 50)', max_digits=5)),
                ('final_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Final combined percentage (0-100)', max_digits=5)),
                ('final_risk_level', models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Final risk level', max_length=20)),
                ('final_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='needs_review', help_text='Final status (Passed/Failed/Needs Review)', max_length=20)),
                ('final_comment', models.TextField(blank=True, help_text='Final comment based on results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated inspection', on_delete=django.db.models.deletion.CASCADE, related_name='final_score', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Final Score Summary',
                'verbose_name_plural': 'Final Score Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostChecklistScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_behavior_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Score for trip behavior monitoring', max_digits=5)),
                ('trip_behavior_max', models.DecimalField(decimal_places=2, default=Decimal('12'), help_text='Max score for trip behavior', max_digits=5)),
                ('trip_behavior_questions', models.IntegerField(default=12)),
                ('trip_behavior_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('trip_behavior_risk', models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', max_length=20)),
                ('driving_behavior_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Score for driving behavior check', max_digits=5)),
                ('driving_behavior_max', models.DecimalField(decimal_places=2, default=Decimal('11'), help_text='Max score for driving behavior', max_digits=5)),
                ('driving_behavior_questions', models.IntegerField(default=11)),
                ('driving_behavior_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('driving_behavior_risk', models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', max_length=20)),
                ('post_trip_report_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Score for post-trip report', max_digits=5)),
                ('post_trip_report_max', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Max score for post-trip report', max_digits=5)),
                ('post_trip_report_questions', models.IntegerField(default=5)),
                ('post_trip_report_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('post_trip_report_risk', models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total post-checklist score', max_digits=5)),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=Decimal('28'), help_text='Maximum possible post-checklist score', max_digits=5)),
                ('total_questions', models.IntegerField(default=28)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overall post-checklist percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(help_text='Associated inspection', on_delete=django.db.models.deletion.CASCADE, related_name='post_checklist_score', to='inspections.pretripinspection')),
            ],
            options={
                'verbose_name': 'Post-Checklist Score Summary',
                'verbose_name_plural': 'Post-Checklist Score Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
