# Generated by Django 6.0.1 on 2026-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_add_post_checklist_and_final_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='postchecklistscoresummary',
            name='risk_status',
            field=models.CharField(choices=[('no_risk', 'No Risk'), ('very_low_risk', 'Very Low Risk'), ('low_risk', 'Low Risk'), ('high_risk', 'High Risk')], default='high_risk', help_text='Overall post-checklist risk status', max_length=20),
        ),
    ]
