# Generated by Django 6.0.1 on 2026-01-22 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated vehicle ID in format VEH-XXXX', max_length=20, unique=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle registration number (e.g., ALB 9345)', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(help_text='Vehicle type (e.g., Freight Truck, Van, Pickup)', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the vehicle is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this vehicle record', on_delete=django.db.models.deletion.PROTECT, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(blank=True, help_text='Driver assigned to this vehicle (one-to-one relationship)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle_id'], name='vehicles_ve_vehicle_5ac43f_idx'), models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx'), models.Index(fields=['is_active'], name='vehicles_ve_is_acti_53dbe5_idx')],
            },
        ),
    ]
