# Generated by Django 6.0.1 on 2026-01-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='vehicles_vehicle_id_idx',
            old_name='vehicles_ve_vehicle_5ac43f_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='vehicles_registration_idx',
            old_name='vehicles_ve_registr_3774f3_idx',
        ),
    ]
