# Generated by Django 6.0.1 on 2026-01-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_vehicles_ve_vehicle_5ac43f_idx_vehicles_vehicle_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Small Truck', 'Small Truck'), ('Big Bus', 'Big Bus'), ('Mini Bus', 'Mini Bus'), ('Car', 'Car')], help_text='Vehicle type (Truck, Small Truck, Big Bus, Mini Bus, Car)', max_length=50),
        ),
    ]
