# Generated by Django 6.0.1 on 2026-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_add_vehicle_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_full_service_date',
            field=models.DateField(blank=True, help_text='Last date of full service based on manufacturing mileage', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_partial_service_date',
            field=models.DateField(blank=True, help_text='Last date of partial service based on manufacturing mileage', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_vehicle_maintenance_date',
            field=models.DateField(blank=True, help_text='Last date of vehicle maintenance based on trip', null=True),
        ),
    ]
