# Generated by Django 6.0.1 on 2026-01-22 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated driver ID in format DRV-XXXX', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(db_index=True, help_text="Driver's license number (must be unique)", max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number with country code (e.g., +260971234567)', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the driver is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this driver record', on_delete=django.db.models.deletion.PROTECT, related_name='created_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_id'], name='drivers_dri_driver__6af68b_idx'), models.Index(fields=['license_number'], name='drivers_dri_license_ce5f7e_idx'), models.Index(fields=['is_active'], name='drivers_dri_is_acti_7c5f39_idx')],
            },
        ),
    ]
