# Generated by Django 6.0.1 on 2026-01-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driver',
            new_name='drivers_driver_id_idx',
            old_name='drivers_dri_driver__6af68b_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='drivers_license_idx',
            old_name='drivers_dri_license_ce5f7e_idx',
        ),
    ]
