# Generated by Django 6.0.1 on 2026-01-22 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated mechanic ID in format MECH-XXXX', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(help_text="Mechanic's specialization (e.g., General Mechanic, Diesel Specialist)", max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number with country code (e.g., +260977654321)', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the mechanic is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this mechanic record', on_delete=django.db.models.deletion.PROTECT, related_name='created_mechanics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mechanic',
                'verbose_name_plural': 'Mechanics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic_id'], name='mechanics_m_mechani_cd48ab_idx'), models.Index(fields=['is_active'], name='mechanics_m_is_acti_03eba4_idx')],
            },
        ),
    ]
