# Generated by Django 6.0.1 on 2026-01-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mechanic',
            new_name='mechanics_mechanic_id_idx',
            old_name='mechanics_m_mechani_cd48ab_idx',
        ),
    ]
