# Generated by Django 6.0.1 on 2026-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_rename_mechanics_m_mechani_cd48ab_idx_mechanics_mechanic_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='certification_status',
            field=models.CharField(choices=[('certified', 'Certified'), ('not_certified', 'Not Certified')], default='not_certified', help_text='Certification status of the mechanic', max_length=20),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_full_service_date',
            field=models.DateField(blank=True, help_text='Last date of full service based on manufacturing mileage', null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_partial_service_date',
            field=models.DateField(blank=True, help_text='Last date of partial service based on manufacturing mileage', null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='last_vehicle_maintenance_date',
            field=models.DateField(blank=True, help_text='Last date the mechanic performed vehicle maintenance based on trip', null=True),
        ),
    ]
