# Generated by Django 6.0.1 on 2026-02-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_mechanic_certification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='last_full_service_date',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='last_partial_service_date',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='last_vehicle_maintenance_date',
        ),
    ]
